### ISSUE TITLE
Fan PID

### ISSUE THREAD

**Issue by waldo3000** [UnifiedEngineering/T-962-improvements#10]
In general, the PID for the fan and lamp do a good job of making the actual temperature track the profile. However, at the peak of the profile when the temperature starts to go down, the fan startup is delayed and this results in a longer period of time spent at the peak temperature.  Is it possible to change the fan PID to make the fan more responsive?

**Comment by rogerclarkmelbourne** [comment]
Was there any progress on improving the PID tuning.

I've just flashed got my T-962 and flashed the latest firmware, and have run the oven a few times to test how well the Actual values track the Set values, and I'm generally seeing that the Actual temperature is about 5 degrees below the Set value, when the temperature ramps up.

The only time I see a slight overshoot is at the very peak of the reflow.

It looks like the PID needs to have a bit more gain (but I'm not an expert in PID).

I wonder if it would be worth adding the PID tuning values to one of the menus.
I'll probably for the code and have a go at doing this myself.
I've compiled and reflashed the existing code, and I'm familiar with embedded programming - however I'm not sure how easy its going to be to make the setting menu scroll up and down to accomodate new settings  ;-)

**Comment by janekx** [comment]
+1 to able to tune FAN PID too.

**Comment by rogerclarkmelbourne** [comment]
@waldo3000

I've been doing a load of test with 5 different thermocouples, either connected to the oven, or to a DMM with thermocouple input.

But consistency between the thermocouples is very poor.

I have given up using the opamp sensing electronics on the control board and I'm using Max31855 interfaces, but this doesn't seem to  help a lot.

Ive now ordered another 5 themocouples from eBay, and I have 4 Max31855 interfaces, which I'm going to connect to a separate microcontroller board (STM32) and I'm going to see what results I get using a separate system to read the values.

I'v also modified by fork of the firmware so I can use offset and gain on the Max31855 inputs, as that feature was not available in the main version (here)

BTW. It should not be too difficult to put PID parameters into the Settings, as I already had to do this so that all 4 of the possible Max31855 inputs can have these corrects applied to them, and it was not too hard to add the the codebase

**Comment by xnk** [comment]
Issue cleanup

**Comment by rogerclarkmelbourne** [comment]
In the end, going to all this trouble didnt really help, as I still got loads of hotspots in the oven, which made it unusable for me.

1 year on, I'm now starting to think about fitting a proper convection fan, but that's an engineering job not a electronics or programming problem
