### ISSUE TITLE
New version T962

### ISSUE THREAD

**Issue by BGuiGui** [UnifiedEngineering/T-962-improvements#239]
Hi,
Is there something different on the bootloader of the new version of T962 ?
I didn't succeed to flash the firmware.
I did a lot of try and finally buy a new ftdi, but it isn't better. I try in Linux and windows.

I can boot on bootloader mode with the n_ISP pin and F1 hold at powering. But the screen obtain seem different from what I read on the net (see attached file). I have a "T962" write in middle and "Infrared IC heater; www.electron-tools.com" write above
![IMG_20230222_131001](https://user-images.githubusercontent.com/123058550/220616186-fe5502a7-dc20-4c2d-8e20-5966f7a884e8.jpg)
Any help please ?! Is that screen normal for a bootloader mode ?

**Comment by BGuiGui** [comment]
I am sorry. I take time to test all combination of baudrate etc, and finally succeed, so I have my response, this screen was normal !
Let's start cooking with mister White

**Comment by borland1** [comment]
BGuiGui,

The bootloader is built in the MCU, so the bootloader is independent of the original firmware provided by the oven manufacturer or any subsequent firmware flashed on it.  The repository firmware here only provides a startup hook that loads the bootloader when F1 key is pressed on power up. 

Since you figured out your firmware flashing mistakes, please **CLOSE** this **ISSUE** to remove unhelpful clutter.
