### ISSUE TITLE
Addition of buffering for serial, Change to default baud rate

### ISSUE THREAD

**Issue by colinoflynn** [UnifiedEngineering/T-962-improvements#25]
I've added a pull request with some initial serial buffering code, which will make parsing messages much easier. I've also changed the default baud rate - I don't know what the thoughts on this are? I'm going back to ye old 115200, as some (such as my) serial USB converter don't support 2MB/s.

This avoids using interrupts since some of the other code isn't interrupt-safe. But it's almost as good.

With the buffering code there's no problems about hanging in printf() statements. If you push too much data it will just drop it however - can change that to block if you want, but it's an easy way to check if the baud rate is sufficient...

**Comment by colinoflynn** [comment]
I've committed this to my branch (see https://github.com/colinoflynn/T-962-improvements/tree/irq-integration). I changed the default baud to 230k - there was an occasional WDT reset with 115k baud. But I haven't done much other testing yet so if you get a chance try running it in your oven.

**Comment by xnk** [comment]
I have now run a few successful reflow sequences at 115k2 with this code without any watchdog bites, but I did notice that there are ways to make this code fall over, triggering the watchdog bite. Sending large amount of RX data to it triggers an almost immediate bite.

Just out of curiosity I set the baudrate really low (9k6, U0DLM=1, U0DLL=194) and increased the watchdog timeout to 4 seconds (9k6 is more than enough to sustain the normal UART flow). I can see that the code actually gets stuck (and just sits there for 4 seconds until watchdog bites) 5 to 20 seconds after boot. Initial startup will look garbled at that low speed, that can be ignored. There's got to be a timing issue with re-enabling or disabling the sub-interrupts going on here..

Also I think it's better to actually check the correct bit in uart_putc:
add_to_circ_buf(&txbuf, thebyte, !!(VICIntEnable & (1<<VIC_UART0)));
(and update the comment about always calling it in blocking mode).

I don't have a solution to the wdog bite issue yet, but increasing baud rate to 230k will not solve the actual issue. Do you have any ideas as to why it would get stuck? Try running it at 9k6 and see if you get similar results. I'll think about it some more and see if there's anything obvious..

**Comment by colinoflynn** [comment]
Alright good to know a method of forcing the WDT reset! Will take a look in a bit - I suspect the main issue might be that it needs portions of the circular buffering code to be atomic, as I had copied that code from the polling branch which didn't care about interrupts. I had just remembered that...

**Comment by colinoflynn** [comment]
Just as an update - I've got a new branch with some debug tests in it, but remain unsure where the underlying issue is. I made the circular buffer stuff interrupt-safe (for now which means it never blocks, and always drops characters if no room), and also added a spurious interrupt handler for the RX interrupt. I don't think I'll have a chance to look at this more for a few days at least, so will leave this as-is for now.

Note that if I disable the onewire code I don't have problems either (i.e. force onewire discovered devices to be 0). It may be some issue with enabling/disabling interrupts somewhere there too. I don't think this is being caused by the spurious interrupt, as it sounds like it's going into a loop, whereas I would expect a spurious interrupt to produce an immediate reset type error (at least without the handler programmed).

**Comment by xnk** [comment]
Hmm, interesting! I'll dive in and see if I can find out what might be wrong with enabling/disabling interrupts. As the issue seems to disappear when onewire isn't constantly fiddling with it that sure sounds reasonable! I spent some time adding simple exception handling to the startup code to make sure that we didn't get stuck because of some data abort or something - turns out that we did not.

**Comment by xnk** [comment]
By the way, no irq disable/restore calls are needed around the initial wd feed instructions in main as the vic isn't enabled yet, just noticed that commit. I'm continuing my investigation, this is probably (as always) some mundane detail gone wrong.. :)

**Comment by xnk** [comment]
I think I have it figured out.. I changed the way interrupts were disabled (turn them off at the core level instead of using the VIC) which helped the situation, the I minimized the amount of time spent with IRQs disabled during OneWire operations. You can now run with a 256 byte buffer at 9600 bps (using divisor 360) and it will chug along just fine. I pulled in the stuff from irq-integration fork into my irq-integration branch together with some fixes.

Now I think we're close to merging it onto master - I'll let the code run for a while in my oven here and see if it acts up first. Anyone else are more than welcome to try the code from the irq-integration branch out as well and report any oddities. I updated the rest of the functionality from master as well so right now irq-integration is ahead.

I could not make the code misbehave even when throwing garbage into the RX path either (should be ignored, which it seemed to be)

**Comment by colinoflynn** [comment]
Great news! I don't know how SRAM usage is, but you can turn down the buffer size if required too. Thanks for finding that issue out, nice to have it all merged back in.

**Comment by xnk** [comment]
I had the buffer size all the way up to 4096 bytes (times 2) at one point with plenty of spare RAM still. :) The rest of bss plus initialized data is less than 2kB out of the available 16kB. I think 256 bytes is a good number for now, it's the smallest rounded-up power-of-two size that can deal with two full lines of logging output without stalling (during reflow mode switching for example).
